# Live Firebase
# Variables:
#   -baseUrl: API base URL
#   -API KEY: project API key obtained from Firebase console (website)
#   -accountUrl: base URL for authentication from Firebase
@baseUrl = https://us-central1-mvvm-frontend-and-mvc-backend.cloudfunctions.net/api
@API_KEY = AIzaSyDHnf0CVVPULD5PHaNe2Hn-cgUXkSJtdZU
@accountUrl = https://identitytoolkit.googleapis.com/v1/accounts

### Request 1: Sign up with email / password
# POST https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=[API_KEY]
# Documentation:  https://firebase.google.com/docs/reference/rest/auth

POST {{accountUrl}}:signUp?key={{API_KEY}}
Content-Type: application/json

{
    "email": "anyone123@mockmail.com",
    "password": "abc123",
    "returnSecureToken": true
}

### Request 2 Sign in with email and password
# https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=[API_KEY]

POST {{accountUrl}}:signInWithPassword?key={{API_KEY}}
Content-Type: application/json

{
    "email": "alex@mockmail.com",
    "password": "abc123",
    "returnSecureToken": true
}

# The following request are done yet. The routes in the backend
#  are still not protected yet. to be done later.
#  Each consequence request must be included with access token

@accessToken = eyJhbGciOiJSUzI1NiIsImtpZCI6ImFiMGNiMTk5Zjg3MGYyOGUyOTg5YWI0ODFjYzJlNDdlMGUyY2MxOWQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiQWxleGFuZGVyIEhvbG1lcyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9tdnZtLWZyb250ZW5kLWFuZC1tdmMtYmFja2VuZCIsImF1ZCI6Im12dm0tZnJvbnRlbmQtYW5kLW12Yy1iYWNrZW5kIiwiYXV0aF90aW1lIjoxNjIzMTY4NjA3LCJ1c2VyX2lkIjoiYWxleCIsInN1YiI6ImFsZXgiLCJpYXQiOjE2MjMxNjg2MDcsImV4cCI6MTYyMzE3MjIwNywiZW1haWwiOiJhbGV4QG1vY2ttYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhbGV4QG1vY2ttYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.GTFu4fw2qODX4iFnq86BDF8yVmxNEBuTJshiNNsBSvTS1l8K5-sVAJTGbCF4gaSunGjlA2qNtks2s24SqI8-zGi671TqV7ymd-YQERz_A1tPZviuEPnJUYuvtqLpE9ibjXu0QgvVbINJAmzUDTZl1QEG8RvAuaCn6oH5_9aLq8NzFefDkD_cr1P6C11jOy9U34a9DkB51LeJPJkE5lr5sQnioHQnu-6BgScUfBa7pQCl8vBNvnlzSXiUo5YGw-G0RCh4o38qVo4cwnwWHj49C_mw6opSA8vcA95nh8zJjHunObkgLL0rHiK6pI3zu4qkDtjMMJEUKPsW8eTGEAHncw

### Request 3 : Get the counter data  for a given user
GET {{baseUrl}}/counters?user=user2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Request 3 : Update the information of a given counter
PUT {{baseUrl}}/counters/counter1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "user": "user1",
    "counter": 2
}

### Request: Get all users
GET {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Request: Add a new user
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "login": "user4",
    "password": "123",
    "name": "John Doe",
    "id": "user4"
}

### Request: Delete a user
DELETE {{baseUrl}}/users/M0USorawg6O3xJawA8i7
Content-Type: application/json
Authorization: Bearer {{accessToken}}