### Use this file to test out your REST call before implementing them in the code

### Change the IP address below to your PC's IP address. Remain the port number 3000 unchanged
@baseUrl = http://192.168.0.5:3000

### Request 1 : Get a user whose correct 'login' and 'password'
### Purpose   : To simulate the authentication process. 
GET {{baseUrl}}/users?login=alex&password=123x

### Request 2 : Get the counter data  for a given user
GET {{baseUrl}}/counters?user=2

### Request 3 : Update the information of a given counter
PUT {{baseUrl}}/counters/2
Content-Type: application/json

{
    "user": 2,
    "counter": 2
}
